# Generated by Django 4.0.4 on 2022-05-26 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Countries', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Flights', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'customer')},
        ),
    ]
