# Generated by Django 4.0.4 on 2022-06-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_credit_card'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='accounts.user'),
        ),
    ]
