# Generated by Django 4.0.4 on 2022-09-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Canceled', 'Canceled')], default='Booked', max_length=50),
        ),
    ]
