# Generated by Django 4.0.4 on 2022-06-27 20:06

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.MinimumLengthValidator, django.contrib.auth.password_validation.NumericPasswordValidator], verbose_name='Password'),
        ),
    ]
