# Generated by Django 4.0.4 on 2022-06-27 20:21

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[accounts.models.NumericValidator, django.core.validators.MinLengthValidator(6)], verbose_name='Password'),
        ),
    ]
