# Generated by Django 4.0.4 on 2022-06-27 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{15}$', 'Invalid Credit Card')]),
        ),
    ]
